load("@rules_go//go:def.bzl", "go_library", "go_test")

exports_files(
    ["THIRD_PARTY_LICENSES.txt"],
    visibility = ["//visibility:public"],
)

go_library(
    name = "licenses",
    srcs = ["licenses.go"],
    embedsrcs = ["THIRD_PARTY_LICENSES.txt"],
    importpath = "git-review/internal/licenses",
    visibility = ["//cmd:__subpackages__"],
)

go_test(
    name = "licenses_test",
    srcs = ["licenses_test.go"],
    embed = [":licenses"],
)
