load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "httpapi",
    srcs = ["httpapi.go"],
    importpath = "git-review/internal/httpapi",
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "httpapi_test",
    srcs = ["httpapi_test.go"],
    embed = [":httpapi"],
)
